version: '3.8'

services:
  dev-app:
    build:
      context: .
      target: development
    container_name: vue-dev-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  db_data: {} # 'db' 서비스에서 사용할 볼륨 정의