version: '3.8'

services:
  # 1. NGINX 리버스 프록시 서비스
  nginx:
    image: nginx:alpine
    container_name: psc_nginx
    ports:
      - "8082:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    restart: always

  # 2. PostgreSQL 데이터베이스 서비스
  db:
    image: postgres:17-alpine
    container_name: psc_db
    environment:
      POSTGRES_DB: salarydb
      POSTGRES_USER: salary_user
      POSTGRES_PASSWORD: P@ssWord!123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    restart: always

  # 3. Spring Boot 백엔드 서비스
  backend:
    image: ghcr.io/jiho-beh/personal_finance_simulation/backend:latest
    container_name: psc_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/salarydb
      SPRING_DATASOURCE_USERNAME: salary_user
      SPRING_DATASOURCE_PASSWORD: P@ssWord!123
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - db
    networks:
      - app-network
    restart: on-failure

  # 4. Vue.js 프론트엔드 서비스 (volumes 설정 제거)
  frontend:
    image: ghcr.io/jiho-beh/personal_finance_simulation/frontend:latest
    container_name: psc_frontend
    depends_on:
      - backend
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge

volumes:
  db_data: {}